AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shorten-app

Globals:
  Function:
    Timeout: 10
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      OpenApiVersion: '2.0'

  GenerateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_short_url/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GenerateShortUrl:
          Type: Api
          Properties:
            Path: /api/generate-short-url
            Method: post
            RestApiId: !Ref MyApi

  GetUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_url/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetUrl:
          Type: Api
          Properties:
            Path: /link/{short_url}
            Method: get
            RestApiId: !Ref MyApi

  DynamoDBFullAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource: "*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref DynamoDBFullAccessPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UrlShortenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortenTable
      AttributeDefinitions:
        - AttributeName: short_url
          AttributeType: S
      KeySchema:
        - AttributeName: short_url
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
